// pkg-3 (OpenFic 写作平台) 挂载后验证：按 pkg-19-changelog.md 清单
const { chromium } = require('C:/Users/zhao/AppData/Roaming/npm/node_modules/@playwright/mcp/node_modules/playwright')
const fs = require('fs')
const path = require('path')
const BASE = process.env.MOFEI_BASE || 'http://127.0.0.1:3080'
const OUT = path.join(__dirname, 'verify-shots')
const DATA_DIR = 'E:/Users/zhao/Desktop'
const SESSION_ID = 'session-62a01ca8-ef2a-4da4-b42d-f41369b2cabe'
const ts = String(Date.now()).slice(-6)
const PROJ = '平台验证-' + ts
const CH1 = '第一章-' + ts
const CH2 = '第二章-' + ts
let failures = 0
function log(m) { console.log(m) }
function fail(m) { failures += 1; console.log('FAIL: ' + m) }
function readJson(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch (e) { return null } }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function ensureClientLoaded(page) {
  if (await page.locator('button.of8-open.of8-float').first().isVisible().catch(() => false)) return true
  const badge = page.locator('button', { hasText: 'Cordis Plugin' }).first()
  await badge.waitFor({ state: 'visible', timeout: 15000 })
  await badge.click()
  await sleep(1800)
  await page.locator('button[data-cordis-switch="run"]').first().click()
  await sleep(6000)
  // 若面板仍开着，再点一次 badge 关闭（force 绕过浮层遮挡）
  const panelEl = page.locator('.Nqubda_panel, [class*="Nqubda_panel"]')
  if (await panelEl.count() && await panelEl.first().isVisible().catch(() => false)) {
    await badge.click({ force: true }).catch(() => {})
    await sleep(600)
  }
  return page.locator('button.of8-open.of8-float').first().isVisible().catch(() => false)
}

async function openWorkspace(page) {
  await page.locator('button.of8-open.of8-float').first().click()
  await page.locator('section.of8-panel').waitFor({ state: 'visible', timeout: 10000 })
}

function projectRow(page, title) { return page.locator('.of8-item', { hasText: title }).first() }
function chapterRow(page, title) { return page.locator('.of8-item', { hasText: title }).first() }

;(async () => {
  fs.mkdirSync(OUT, { recursive: true })
  const browser = await chromium.launch({ channel: 'msedge' })
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  await context.addInitScript((sid) => {
    try { localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: sid })) } catch (e) {}
  }, SESSION_ID)
  const pageA = await context.newPage()
  pageA.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)))
  await pageA.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await sleep(9000)
  if (!(await ensureClientLoaded(pageA))) { fail('Client 未装载'); process.exit(1) }
  log('== 1. 入口 + 打开工作区 ==')
  await openWorkspace(pageA)
  const panelBg = await pageA.evaluate(() => getComputedStyle(document.querySelector('.of8-panel')).backgroundColor)
  log('面板背景: ' + panelBg + (panelBg === 'rgba(0, 0, 0, 0)' ? ' (透明!)' : ' (不透明 ok)'))
  await pageA.screenshot({ path: path.join(OUT, 'p3-01-workspace.png') })

  log('== 2. 创建项目/章节 + 草稿写入 ==')
  const projCol = pageA.locator('aside.of8-col').nth(0)
  const chapCol = pageA.locator('aside.of8-col').nth(1)
  await projCol.locator('button', { hasText: '+ 新建' }).click()
  await projCol.locator('input.of8-input').fill(PROJ)
  await projCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  if (await projectRow(pageA, PROJ).count() === 0) fail('项目未创建')
  await chapCol.locator('button', { hasText: '+ 新建' }).click()
  await chapCol.locator('input.of8-input').fill(CH1)
  await chapCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  const editor = pageA.locator('textarea.of8-text')
  const text1 = '第一版正文内容-' + ts
  await editor.fill(text1)
  await sleep(1600)
  let drafts = readJson(path.join(DATA_DIR, '.openfic-drafts.json'))
  log('草稿文件: ' + JSON.stringify(drafts && drafts.items.map((i) => i.content)))
  if (drafts && drafts.items.some((i) => i.content === text1)) log('DRAFT-OK')
  else fail('草稿未落盘')

  log('== 3. 保存 → r2 + 今日字数 + 历史 ==')
  await pageA.locator('button', { hasText: '保存正文' }).click()
  await sleep(1800)
  let projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  let pj = projects.projects.find((p) => p.title === PROJ)
  let ch = pj.chapters.find((c) => c.title === CH1)
  const stats1 = readJson(path.join(DATA_DIR, '.openfic-stats.json'))
  log('保存后: version=' + projects.version + ' revision=' + ch.revision + ' history=' + ch.history.length + ' stats=' + JSON.stringify(stats1 && stats1.days))
  if (projects.version === 3 && ch.revision === 2 && ch.history.length === 1) log('SAVE-R2-OK (v3 + r2 + history r1)')
  else fail('保存异常: version=' + projects.version + ' r=' + ch.revision + ' hist=' + ch.history.length)
  if (stats1 && Object.keys(stats1.days).length > 0) log('STATS-OK')
  else fail('stats 文件未生成')
  const footText = ((await pageA.locator('.of8-foot').textContent()) || '').replace(/\s+/g, ' ')
  log('页脚: ' + footText)
  if (footText.includes('今日 +') && footText.includes('累计')) log('STATS-FOOT-OK')
  else fail('页脚统计缺失')
  const text2 = '第一版正文内容-' + ts + '，第二版补充-' + ts
  await editor.fill(text2)
  await sleep(1400)
  await pageA.locator('button', { hasText: '保存正文' }).click()
  await sleep(1800)
  projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  ch = projects.projects.find((p) => p.title === PROJ).chapters.find((c) => c.title === CH1)
  log('第二次保存: revision=' + ch.revision + ' history=' + ch.history.length)
  if (ch.revision === 3 && ch.history.length === 2) log('SAVE-R3-OK')
  else fail('第二次保存异常')

  log('== 4. 历史面板 + 回滚 ==')
  await pageA.locator('button.of8-mini', { hasText: '历史' }).first().click()
  await sleep(1500)
  const histItems = pageA.locator('.of8-hist-item')
  const histCount = await histItems.count()
  log('历史条目数: ' + histCount)
  const histTexts = []
  for (let i = 0; i < histCount; i++) histTexts.push(((await histItems.nth(i).textContent()) || '').replace(/\s+/g, ' ').slice(0, 40))
  log('历史: ' + JSON.stringify(histTexts))
  if (histCount >= 2 && histTexts[0].includes('r2') && histTexts[1].includes('r1')) log('HISTORY-OK (新→旧)')
  else fail('历史列表异常')
  await pageA.screenshot({ path: path.join(OUT, 'p3-02-history.png') })
  // 回滚 r2（两击）
  await pageA.locator('.of8-hist-item', { hasText: 'r2' }).locator('button.of8-mini').first().click()
  await sleep(500)
  await pageA.locator('.of8-hist-item', { hasText: 'r2' }).locator('button.of8-mini').first().click()
  await sleep(1500)
  const rolled = await editor.inputValue()
  projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  ch = projects.projects.find((p) => p.title === PROJ).chapters.find((c) => c.title === CH1)
  log('回滚后: value=' + rolled + ' revision=' + ch.revision + ' history=' + ch.history.length)
  if (rolled === text1 && ch.revision === 4) log('ROLLBACK-OK (回到第一版, r4)')
  else fail('回滚异常: ' + rolled)

  log('== 5. 章节排序 / 重命名 / 删除 ==')
  await chapCol.locator('button', { hasText: '+ 新建' }).click()
  await chapCol.locator('input.of8-input').fill(CH2)
  await chapCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  // 第二章 上移
  await chapterRow(pageA, CH2).locator('button.of8-mini', { hasText: '↑' }).click()
  await sleep(1200)
  const chapTitles = await pageA.evaluate(() => Array.from(document.querySelectorAll('aside.of8-col:nth-child(2) .of8-title')).map((b) => b.textContent.trim()))
  log('章节顺序: ' + JSON.stringify(chapTitles))
  if (chapTitles[0].startsWith('第二章')) log('MOVE-OK')
  else fail('排序失败')
  // 重命名第二章
  await chapterRow(pageA, CH2).locator('button.of8-mini', { hasText: '✎' }).click()
  await sleep(400)
  const renameInput = pageA.locator('input.of8-rename')
  await renameInput.fill('第二章改名-' + ts)
  await renameInput.press('Enter')
  await sleep(1200)
  if (await chapterRow(pageA, '第二章改名-' + ts).count()) log('RENAME-OK')
  else fail('重命名失败')
  // 删除第二章（两击）
  await chapterRow(pageA, '第二章改名-' + ts).locator('button.of8-mini', { hasText: '×' }).click()
  await sleep(400)
  await chapterRow(pageA, '第二章改名-' + ts).locator('button.of8-mini', { hasText: '×' }).click()
  await sleep(1500)
  if (await chapterRow(pageA, '第二章改名-' + ts).count() === 0) log('DELETE-OK')
  else fail('删除失败')
  await pageA.screenshot({ path: path.join(OUT, 'p3-03-manage.png') })

  log('== 6. 项目重命名 + 目标字数 ==')
  await projectRow(pageA, PROJ).locator('button.of8-mini', { hasText: '✎' }).click()
  await sleep(400)
  await pageA.locator('input.of8-rename').fill(PROJ + '-改名')
  await pageA.locator('input.of8-rename').press('Enter')
  await sleep(1200)
  if (await projectRow(pageA, PROJ + '-改名').count()) log('PROJ-RENAME-OK')
  else fail('项目重命名失败')
  await pageA.locator('.of8-goal-btn').click()
  await sleep(400)
  await pageA.locator('.of8-goal').locator('input.of8-input').fill('1000')
  await pageA.locator('.of8-goal').locator('button', { hasText: '设置' }).click()
  await sleep(1200)
  const goalText = ((await pageA.locator('.of8-goal-btn').textContent()) || '').replace(/\s+/g, ' ')
  log('目标按钮: ' + goalText)
  if (goalText.includes('1000')) log('GOAL-OK')
  else fail('目标字数设置失败')

  log('== 7. Ctrl+S + 专注模式 ==')
  // 删除的是第二章（当时选中），重新选择第一章
  await chapterRow(pageA, CH1).locator('button.of8-title').click()
  await sleep(1000)
  const text3 = 'Ctrl+S 保存内容-' + ts
  await editor.fill(text3)
  await sleep(400)
  await editor.press('Control+s')
  await sleep(1800)
  projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  ch = projects.projects.find((p) => p.title === PROJ + '-改名').chapters.find((c) => c.title === CH1)
  log('Ctrl+S 后: revision=' + ch.revision)
  if (ch.revision === 5) log('CTRL-S-OK')
  else fail('Ctrl+S 未保存: r=' + ch.revision)
  await pageA.locator('button.of8-mini', { hasText: '专注' }).click()
  await sleep(800)
  const focusOn = await pageA.evaluate(() => document.querySelector('.of8-panel').classList.contains('of8-focus'))
  const colsHidden = await pageA.evaluate(() => getComputedStyle(document.querySelectorAll('.of8-col')[0]).display === 'none')
  log('专注模式: class=' + focusOn + ' 左栏隐藏=' + colsHidden)
  if (focusOn && colsHidden) log('FOCUS-OK')
  else fail('专注模式异常')
  await pageA.locator('button.of8-mini', { hasText: '退出专注' }).click()
  await sleep(600)
  await pageA.screenshot({ path: path.join(OUT, 'p3-04-ctrl-s-focus.png') })

  log('== 8. 冲突保护 ==')
  const localText = '平台冲突本地草稿-' + ts
  await editor.fill(localText)
  await sleep(1600)
  const pageB = await context.newPage()
  await pageB.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await sleep(8000)
  if (!(await ensureClientLoaded(pageB))) { fail('页面B Client 未装载'); process.exit(1) }
  await openWorkspace(pageB)
  await pageB.locator('.of8-item', { hasText: PROJ + '-改名' }).first().click()
  await sleep(900)
  await pageB.locator('.of8-item', { hasText: CH1 }).first().click()
  await sleep(900)
  const remoteText = '平台冲突远端保存-' + ts
  await pageB.locator('textarea.of8-text').fill(remoteText)
  await sleep(400)
  await pageB.locator('button', { hasText: '保存正文' }).click()
  await sleep(1800)
  await pageA.locator('button', { hasText: '保存正文' }).click()
  await sleep(1800)
  const alertText = ((await pageA.locator('.of8-alert').textContent()) || '').replace(/\s+/g, ' ')
  projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  ch = projects.projects.find((p) => p.title === PROJ + '-改名').chapters.find((c) => c.title === CH1)
  log('冲突提示: ' + alertText + ' | 文件: r=' + ch.revision + ' content=' + ch.content)
  if (alertText.includes('远端正文已更新') && ch.content === remoteText) log('CONFLICT-OK')
  else fail('冲突保护异常')
  await pageA.screenshot({ path: path.join(OUT, 'p3-05-conflict.png') })
  await pageA.locator('button', { hasText: '使用远端正文' }).click()
  await sleep(1000)
  if ((await editor.inputValue()) === remoteText) log('RESOLVE-OK')
  else fail('冲突解决失败')

  log('== 9. 数据文件最终状态 ==')
  projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  const projF = projects.projects.find((p) => p.title === PROJ + '-改名')
  const chF = projF.chapters.find((c) => c.title === CH1)
  const statsF = readJson(path.join(DATA_DIR, '.openfic-stats.json'))
  log('projects: version=' + projects.version + ' | chapter r=' + chF.revision + ' hist=' + chF.history.length + ' goal=' + projF.goal)
  log('stats days: ' + JSON.stringify(statsF && statsF.days))
  if (projects.version === 3 && chF.history.length >= 4 && projF.goal === 1000 && statsF) log('DATA-V3-OK')
  else fail('数据文件异常')
  await browser.close()
  console.log(failures === 0 ? '== ALL PASS ==' : failures + ' FAILURES')
  process.exit(failures === 0 ? 0 : 1)
})().catch((e) => { console.error('SCRIPT ERROR: ' + (e && e.stack || e)); process.exit(2) })
