// 固定插件验收：client 自动加载 + v4 UI（卷/角色/笔记/搜索）交互验证
const { chromium } = require('C:/Users/zhao/AppData/Roaming/npm/node_modules/@playwright/mcp/node_modules/playwright')
const fs = require('fs')
const path = require('path')
const BASE = process.env.MOFEI_BASE || 'http://127.0.0.1:3080'
const OUT = path.join(__dirname, 'verify-shots')
const DATA_DIR = 'E:/Users/zhao/Desktop'
const SESSION_ID = 'session-62a01ca8-ef2a-4da4-b42d-f41369b2cabe'
const ts = String(Date.now()).slice(-6)
const PROJ = '固定版验证-' + ts
let failures = 0
function log(m) { console.log(m) }
function fail(m) { failures += 1; console.log('FAIL: ' + m) }
function readJson(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch (e) { return null } }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

;(async () => {
  fs.mkdirSync(OUT, { recursive: true })
  const browser = await chromium.launch({ channel: 'msedge' })
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  await context.addInitScript((sid) => {
    try { localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: sid })) } catch (e) {}
  }, SESSION_ID)
  const page = await context.newPage()
  page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)))
  await page.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await sleep(9000)
  log('== 1. client 插件自动加载（无需 Cordis 面板操作） ==')
  const floatBtn = page.locator('button.of8-open.of8-float')
  try {
    await floatBtn.first().waitFor({ state: 'visible', timeout: 30000 })
    log('AUTO-LOAD-OK 浮动按钮直接可见')
  } catch (e) {
    fail('client 未自动加载: ' + e.message)
    // 尝试 Cordis 面板检查是否动态插件复活
    const badge = page.locator('button', { hasText: 'Cordis Plugin' })
    log('Cordis badge count: ' + await badge.count())
    process.exit(1)
  }
  await page.locator('button.of8-side').first().waitFor({ state: 'visible', timeout: 10000 })
  log('SIDEBAR-OK 侧栏入口可见')
  await page.screenshot({ path: path.join(OUT, 'fx-01-loaded.png') })

  log('== 2. 打开工作区 + 创建项目/章节 ==')
  await floatBtn.first().click()
  await page.locator('section.of8-panel').waitFor({ state: 'visible', timeout: 10000 })
  await sleep(1000)
  const panelBg = await page.evaluate(() => getComputedStyle(document.querySelector('.of8-panel')).backgroundColor)
  log('面板背景: ' + panelBg + (panelBg === 'rgba(0, 0, 0, 0)' ? ' (透明!)' : ' (ok)'))
  const projCol = page.locator('aside.of8-col').nth(0)
  const chapCol = page.locator('aside.of8-col').nth(1)
  await projCol.locator('button', { hasText: '+ 新建' }).click()
  await sleep(400)
  await projCol.locator('input.of8-input').fill(PROJ)
  await projCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  if (await page.locator('.of8-item', { hasText: PROJ }).count() === 0) fail('项目未创建')
  await chapCol.locator('button', { hasText: '+ 新建' }).click()
  await sleep(400)
  await chapCol.locator('input.of8-input').fill('第一章-' + ts)
  await chapCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  const editor = page.locator('textarea.of8-text')
  try { await editor.waitFor({ state: 'visible', timeout: 8000 }); log('CHAPTER-EDITOR-OK') } catch (e) { fail('编辑器未出现: ' + e.message) }
  const text1 = '固定版正文-' + ts
  await editor.fill(text1)
  await sleep(1600)
  let drafts = readJson(path.join(DATA_DIR, '.openfic-drafts.json'))
  if (drafts && drafts.items.some((i) => i.content === text1)) log('DRAFT-OK')
  else fail('草稿未落盘')
  // 保存正文（搜索搜的是已保存内容）
  await page.locator('button', { hasText: '保存正文' }).click()
  await sleep(1800)

  log('== 3. 卷：创建卷 + 章节移入卷 ==')
  await chapCol.locator('button.of8-mini', { hasText: '+' }).first().click()
  await sleep(400)
  await chapCol.locator('input.of8-input').fill('第一卷-' + ts)
  await chapCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  const volVisible = await page.locator('.of8-vol', { hasText: '第一卷-' + ts }).count()
  if (volVisible) log('VOLUME-CREATE-OK')
  else fail('卷未创建')
  // 章节移入卷
  const chRow = page.locator('.of8-item', { hasText: '第一章-' + ts }).first()
  await chRow.locator('button.of8-mini', { hasText: '卷' }).click()
  await sleep(400)
  await chRow.locator('select.of8-sel').selectOption({ index: 1 })
  await sleep(1500)
  const inVol = await page.evaluate(() => Array.from(document.querySelectorAll('.of8-vol .of8-item')).some((el) => el.textContent.includes('第一章')))
  log('章节移入卷: ' + (inVol ? 'YES' : 'NO'))
  if (inVol) log('VOLUME-MOVE-OK')
  else fail('章节移卷失败')
  await page.screenshot({ path: path.join(OUT, 'fx-02-volume.png') })

  log('== 4. 角色页签 ==')
  await page.locator('button.of8-tab', { hasText: '角色' }).click()
  await sleep(600)
  await projCol.locator('button', { hasText: '+ 新建' }).click()
  await sleep(400)
  await projCol.locator('input.of8-input').fill('主角-' + ts)
  await projCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  if (await page.locator('.of8-item', { hasText: '主角-' + ts }).count()) log('CHARACTER-CREATE-OK')
  else fail('角色未创建')
  await page.locator('.of8-item', { hasText: '主角-' + ts }).first().locator('button.of8-title').click()
  await sleep(600)
  const charDesc = page.locator('textarea.of8-text')
  await charDesc.fill('性格：冷静果断')
  await sleep(300)
  await page.locator('button', { hasText: '保存角色' }).click()
  await sleep(1500)
  const projects = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  const pj = projects.projects.find((p) => p.title === PROJ)
  const ch = pj && pj.characters.find((c) => c.name === '主角-' + ts)
  if (ch && ch.description === '性格：冷静果断') log('CHARACTER-SAVE-OK')
  else fail('角色描述未保存')
  await page.screenshot({ path: path.join(OUT, 'fx-03-character.png') })

  log('== 5. 笔记页签：分类 + 笔记 + 锁定 ==')
  await page.locator('button.of8-tab', { hasText: '笔记' }).click()
  await sleep(600)
  await projCol.locator('button', { hasText: '+ 分类' }).click()
  await sleep(400)
  await projCol.locator('input.of8-input').fill('设定-' + ts)
  await projCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  if (await page.locator('.of8-vol', { hasText: '设定-' + ts }).count()) log('CATEGORY-OK')
  else fail('分类未创建')
  await page.locator('button.of8-btn.of8-primary', { hasText: '+ 新建笔记' }).click()
  await sleep(400)
  await projCol.locator('input.of8-input').fill('世界观-' + ts)
  await projCol.locator('button', { hasText: '创建' }).click()
  await sleep(1500)
  if (await page.locator('.of8-item', { hasText: '世界观-' + ts }).count()) log('NOTE-CREATE-OK')
  else fail('笔记未创建')
  await page.locator('.of8-item', { hasText: '世界观-' + ts }).first().locator('button.of8-title').click()
  await sleep(600)
  await page.locator('textarea.of8-text').fill('魔法世界，天空之城。')
  await sleep(300)
  await page.locator('button', { hasText: '保存笔记' }).click()
  await sleep(1500)
  await page.locator('button.of8-mini', { hasText: '🔒' }).click()
  await sleep(1500)
  const projects2 = readJson(path.join(DATA_DIR, '.openfic-projects.json'))
  const pj2 = projects2.projects.find((p) => p.title === PROJ)
  const note = pj2 && pj2.notes.find((n) => n.title === '世界观-' + ts)
  if (note && note.content === '魔法世界，天空之城。' && note.isLocked) log('NOTE-SAVE-LOCK-OK')
  else fail('笔记保存/锁定异常: ' + JSON.stringify(note && { content: note.content, isLocked: note.isLocked }))
  await page.screenshot({ path: path.join(OUT, 'fx-04-notes.png') })

  log('== 6. 章节全文搜索 ==')
  await page.locator('button.of8-tab', { hasText: '项目' }).click()
  await sleep(400)
  await chapCol.locator('button', { hasText: '搜索' }).click()
  await sleep(400)
  await chapCol.locator('input.of8-input').fill('固定版正文')
  await sleep(1200)
  const sr = await page.locator('.of8-sr-item').count()
  log('搜索结果: ' + sr)
  if (sr > 0) log('SEARCH-OK')
  else fail('搜索无结果')
  await page.screenshot({ path: path.join(OUT, 'fx-05-search.png') })

  await browser.close()
  console.log(failures === 0 ? '== ALL PASS ==' : failures + ' FAILURES')
  process.exit(failures === 0 ? 0 : 1)
})().catch((e) => { console.error('SCRIPT ERROR: ' + (e && e.stack || e)); process.exit(2) })
