// 墨扉 v0.3.1 UI 回归：Markdown 工具条、章节拖拽排序、写作热力图、AI 历史/批量摘要面板
// 前置：DSH 已重启加载 mofei-dsh v0.3.1
const { chromium } = require('C:/Users/zhao/AppData/Roaming/npm/node_modules/@playwright/mcp/node_modules/playwright')
const path = require('path')
const BASE = process.env.MOFEI_BASE || 'http://127.0.0.1:3080'
const OUT = path.join(__dirname, 'verify-shots')
const SESSION_ID = 'session-62a01ca8-ef2a-4da4-b42d-f41369b2cabe'
const ts = String(Date.now()).slice(-6)
const PROJ = 'v7验证-' + ts
let failures = 0
const log = (m) => console.log(m)
const fail = (m) => { failures += 1; console.log('FAIL: ' + m) }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

;(async () => {
  const browser = await chromium.launch({ channel: 'msedge' })
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  await context.addInitScript((sid) => { try { localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: sid })) } catch (e) {} }, SESSION_ID)
  const page = await context.newPage()
  page.on('pageerror', (e) => console.log('PAGEERROR:', e.message.slice(0, 200)))
  await page.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await sleep(9000)
  await page.locator('button.mf-side').first().waitFor({ state: 'visible', timeout: 30000 })
  await page.locator('button.mf-side').first().click()
  await page.locator('section.mf-panel').waitFor({ state: 'visible', timeout: 10000 })
  await sleep(800)

  log('== 1. 创建项目与两章 ==')
  await page.locator('button.mf-act', { hasText: '项目' }).click()
  await page.locator('.mf-sh button', { hasText: '+ 新建' }).first().click()
  await page.locator('.mf-form input[placeholder="项目名称"]').fill(PROJ)
  await page.locator('.mf-form button', { hasText: '创建' }).click()
  await sleep(1200)
  const chapterAside = page.locator('aside.mf-col').nth(1)
  await chapterAside.locator('.mf-sh button', { hasText: '+ 新建' }).click()
  await page.locator('.mf-form input[placeholder="章节标题"]').fill('第一章')
  await page.locator('.mf-form button', { hasText: '创建' }).click()
  await sleep(800)
  await chapterAside.locator('.mf-sh button', { hasText: '+ 新建' }).click()
  await page.locator('.mf-form input[placeholder="章节标题"]').fill('第二章')
  await page.locator('.mf-form button', { hasText: '创建' }).click()
  await sleep(1000)
  if (await page.locator('.mf-item', { hasText: '第二章' }).count() > 0) log('CHAPTERS-OK')
  else fail('章节创建失败')

  log('== 2. Markdown 工具条 ==')
  await page.locator('.mf-item', { hasText: '第一章' }).first().locator('button.mf-title').click()
  await sleep(600)
  const toolbar = page.locator('.mf-mdtoolbar')
  await toolbar.waitFor({ state: 'visible', timeout: 8000 })
  const editor = page.locator('textarea.mf-text')
  await editor.fill('正文一行')
  await toolbar.locator('button', { hasText: 'H2' }).click()
  await sleep(300)
  const value = await editor.inputValue()
  if (value.includes('## 正文一行')) log('MARKDOWN-TOOLBAR-OK')
  else fail('H2 未应用: ' + value)
  await page.screenshot({ path: path.join(OUT, 'v7-02-markdown.png') })

  log('== 3. 写作热力图 ==')
  await page.locator('.mf-foot button', { hasText: '写作热力图' }).click()
  await sleep(500)
  const heat = page.locator('.mf-heat-grid')
  await heat.waitFor({ state: 'visible', timeout: 8000 })
  const cellCount = await page.locator('.mf-hm-cell').count()
  if (cellCount === 84) log('HEATMAP-OK')
  else fail('热力图格数异常: ' + cellCount)
  await page.screenshot({ path: path.join(OUT, 'v7-03-heatmap.png') })

  log('== 4. 章节拖拽排序 ==')
  const secondRow = page.locator('.mf-item', { hasText: '第二章' }).first()
  const firstRow = page.locator('.mf-item', { hasText: '第一章' }).first()
  await secondRow.dragTo(firstRow)
  await sleep(1000)
  const texts = await page.locator('.mf-item .mf-title').allInnerTexts()
  const order = texts.filter((t) => t.includes('第一章') || t.includes('第二章'))
  if (order.length >= 2 && order[0].includes('第二章')) log('DRAG-REORDER-OK')
  else fail('拖拽排序结果异常: ' + JSON.stringify(order))
  await page.screenshot({ path: path.join(OUT, 'v7-04-drag.png') })

  log('== 5. AI 面板历史/批量摘要按钮 ==')
  await page.locator('.mf-item', { hasText: '第二章' }).first().locator('button.mf-title').click()
  await sleep(400)
  await page.locator('button.mf-mini', { hasText: 'AI 助手' }).click()
  await sleep(400)
  const aiText = await page.locator('.mf-ai').innerText()
  if (aiText.includes('会话历史') && aiText.includes('批量摘要')) log('AI-PANEL-V7-OK')
  else fail('AI 面板缺少历史/批量摘要按钮: ' + aiText.slice(0, 120))

  log('== 6. 清理测试项目 ==')
  const cleanup = await page.evaluate(async (projName) => {
    const call = async (method, args) => fetch('/api/mofei', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ method, args: args || {} }) }).then((r) => r.json())
    const list = await call('list-projects', {})
    const project = list.value.projects.find((p) => p.title === projName)
    if (!project) return false
    await call('delete-project', { projectId: project.id })
    return true
  }, PROJ)
  if (cleanup) log('CLEANUP-OK')
  else fail('清理失败')

  await browser.close()
  console.log(failures === 0 ? '== ALL PASS ==' : failures + ' FAILURES')
  process.exit(failures === 0 ? 0 : 1)
})().catch((e) => { console.error('SCRIPT ERROR: ' + (e && e.stack || e)); process.exit(2) })
